Table A{
  id int [pk]
  name varchar
  email varchar
}

Table B as b {
  id int [pk]
  name varchar [default:"dwadaw"]
  email varchar
}

Table C as c{
  id int [pk]
  b_id int
  name varchar(255)
  email varchar(500)
}



Enum oop {
  aawww
  wwoo
  wwppp 
}

Ref C_to_B: B.id < C.b_id
