Table A{
  id int [pk]
  name varchar
  email varchar
}

Table B as b {
  id int [pk]
  name varchar [default:"dwadaw",de: "wwaa",dep :"wwsss"]
  email varchar
}

Table C as c{
  id int [pk]
  name varchar(255)
  email varchar(500)
}



Enum oop {
  aawww
  wwoo
  wwppp 
}

Ref c_to_d: schema1.C.id < schema1.D.cId

Table D as d{
  id int [pk]
  cId int
  name varchar(abc255)
  email varchar(500)
}
