Enum userStatus{
  active
  ban
}

Enum user_gender{ 
  male
  female
  nonbinary
  prefer_not_to_say
}

Enum venue_state{
  published 
  unpublished 
}

Enum activity_type { 
  all
  exhibition 
  seminar
}

Enum request_status {
  pending 
  accepted 
  rejected 
  finished 
}

Table user {
  id BIGSERIAL [pk]
  username varchar(255) [not null, note: "用户名"]
  email varchar(255) [not null, note: "邮箱，用于登录"]
  
  avatar varchar(255) [note: "头像URL (MVP阶段可简化处理或非强制)"] 
  gender user_gender [default: 'prefer_not_to_say', note:"用户性别 (MVP阶段可简化处理或非强制)"]
  introduce varchar(300) [note: "用户简介 (MVP阶段可简化处理或非强制)"]
  is_show bool [default: false, note: "是否公开显示个人资料 (MVP阶段可简化处理或非强制)"]

  is_delete bool [default: false, note: "软删除标志"]
  status userStatus [default: 'active', note: "用户账户状态"]

  createTime timestamp [default: `now()`, note: "创建时间"]
  updateTime timestamp [note: "更新时间"]
}

Table organizer { 
  id BIGSERIAL [pk]
  user_id BIGSERIAL [not null, unique, note: "外键，关联用户ID"]
  phone varchar(255) [not null, note: "租户/客户联系电话 (MVP中“联系方式”的一部分)"]
  is_delete bool [default: false]

  createTime timestamp [default: `now()`]
  updateTime timestamp 
}

Table lessor { 
  id BIGSERIAL [pk]
  user_id BIGSERIAL [not null, unique, note: "外键，关联用户ID"]
  phone varchar(255) [not null, note: "场地所有者联系电话 (MVP中“联系方式”的一部分)"]
  is_delete bool [default: false]

  createTime timestamp [default: `now()`]
  updateTime timestamp
}

Table venue { 
  id BIGSERIAL [pk]
  lessor_id BIGSERIAL [not null, note: "外键，关联场地所有者ID"]
  name varchar(255) [not null, note: "场地名称"]
  
  description varchar(500) [not null, note: "场地简要描述"] 
  
  address varchar(255) [not null, note: "场地地址"]
  capacity int [not null, default: 0, note: "场地容量"] 
  
  images JSONB [not null, note: "场地图片URL列表 (JSONB数组)"] 
  
  allow_activity JSONB [default: '["all"]', note: "允许的活动类型列表 (JSONB数组，activity_type枚举值)"] 
  
  state venue_state [default: "published", note: "场地发布状态"]

  createTime timestamp [default: `now()`]
  updateTime timestamp
}

Table rental_request { 
  id BIGSERIAL [pk]
  organizer_id BIGSERIAL [not null, note: "外键，关联发起请求的租户/客户ID"]
  venue_id BIGSERIAL [not null, note: "外键，关联请求的场地ID"]
  
  start_time timestamp [not null, note: "期望租赁开始日期和时间"]
  end_time timestamp [not null, note: "期望租赁结束日期和时间"]
  
  activity_type activity_type [not null, default: "all", note: "期望活动类型"]
  request_comments text [note: "租户/客户的补充说明或具体需求 (MVP中简化请求内容)"] 

  status request_status [default: 'pending', note: "租赁请求状态 (待处理/已接受/已拒绝)"]

  createTime timestamp [default: `now()`]
  updateTime timestamp
}

Ref: organizer.user_id > user.id [delete: cascade, update: no action]
Ref: lessor.user_id > user.id [delete: cascade, update: no action]

Ref: venue.lessor_id > lessor.id [delete: cascade, update: no action]

Ref: rental_request.organizer_id > organizer.id [delete: cascade, update: no action]
Ref: rental_request.venue_id > venue.id [delete: cascade, update: no action]

