[default_value]

needs_quotes = [
  "text",
  "varchar",
  "character varying",
  "char",
  "character",

  "timestamp",
  "timestamp without time zone",
  "timestamptz",
  "timestamp with time zone",
  "date",
  "time",
  "time without time zone",
  "timetz",
  "time with time zone",
  "interval",

  "json",
  "jsonb",

  "uuid",

  "inet",
  "cidr",
  "macaddr",
  "macaddr8",

  "xml",

  "enum",      
  "point",     
  "line",
  "lseg",
  "box",
  "path",
  "polygon",
  "circle",
  "array"      
]

no_quotes = [
  "integer",
  "int",
  "int4",
  "smallint",
  "int2",
  "bigint",
  "int8",
  "decimal",
  "numeric",
  "real",
  "float4",
  "double precision",
  "float8",

  "serial",
  "serial4",
  "smallserial",
  "serial2",
  "bigserial",
  "serial8",

  "boolean",
  "bool"
]
