[table]
allow_type=[
  "SMALLINT",
  "INTEGER",
  "INT",
  "BIGINT",
  "DECIMAL",

  "NUMERIC",

  "REAL",
  "DOUBLE PRECISION",
  "SMALLSERIAL",
  "SERIAL",
  "BIGSERIAL",

  "VARCHAR",
  "CHAR",

  "TEXT",

  "TIMESTAMP",

  "TIMESTAMP WITHOUT TIME ZONE",

  "TIMESTAMPTZ",

  "TIMESTAMP WITH TIME ZONE",
  "DATE",

  "TIME",

  "TIME WITHOUT TIME ZONE",

  "TIMETZ",

  "TIME WITH TIME ZONE",

  "INTERVAL",

  "BOOLEAN",
  "BOOL",
  "JSON",
  "JSONB",
  "UUID",
  "BYTEA",
  "INET"
]
allow_name="^[a-zA-Z_][a-zA-Z0-9_]*$"
allow_column_name="^[a-zA-Z_][a-zA-Z0-9_]*$"
allow_column_attr=[
  "pk",
  "primary key",
  "not null",
  "unique",
  "increment",
  "null",
  "default",
  "note",
]

[enum]
allow_name="^[a-zA-Z_][a-zA-Z0-9_]*$"
allow_column_name="^[a-zA-Z_][a-zA-Z0-9_]*$"

[relation]
allow_name="^[a-zA-Z_][a-zA-Z0-9_]*$"
